cmake_minimum_required(VERSION 3.18...3.27)
set(CMAKE_CUDA_ARCHITECTURES 80)
project(gacs_cuda LANGUAGES CXX CUDA)
enable_language(CUDA)
find_package(CUDAToolkit REQUIRED)
find_package(Python 3.8 COMPONENTS Interpreter Development.Module REQUIRED)
if (NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
endif()
set(CMAKE_CUDA_FLAGS_RELEASE "-O3 -lineinfo")
execute_process(COMMAND "${Python_EXECUTABLE}" -m nanobind --cmake_dir
  OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE nanobind_ROOT)
find_package(nanobind CONFIG REQUIRED)
nanobind_add_module(gacs_cuda gacs_cuda.cu)
set_property(TARGET gacs_cuda PROPERTY CUDA_ARCHITECTURES "80")
